### ISSUE TITLE
Beta 0.1.3b1 sensors not appended 

### ISSUE THREAD

**Issue by crowdHalo** [gjohansson-ST/stl#1]
Thank you very much for the recent updates! Regarding the latest beta I get an error when the sensors are to be added:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/stl/binary_sensor.py", line 36, in async_setup_entry
    for device in devices:
TypeError: 'coroutine' object is not iterable `

To clarify; none of my door sensors are shown.

**Comment by gjohansson-ST** [comment]
Mine neither. I didn't really test and just hoped it works 😄 
I will get too it shortly I hope to get this done and out of the way.
It seems to have also made the alarm not properly update so unless you have already go back to the old version.

**Comment by gjohansson-ST** [comment]
Binary sensors are now added in the newly release v0.1.3 version
